------------------------------------------------------------------
--  TABLE COURSE_BELONGS_TO
------------------------------------------------------------------

CREATE TABLE COURSE_BELONGS_TO
(
   COURSE_ID   VARCHAR (10),
   D_ID        VARCHAR (10)
)
NOCACHE
LOGGING;

ALTER TABLE `universitydb`.`COURSE_BELONGS_TO` 
CHANGE COLUMN `COURSE_ID` `COURSE_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `D_ID` `D_ID` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`COURSE_ID`, `D_ID`),
ADD INDEX `COURSE_BELONGS_TO_FK2_idx` (`D_ID` ASC);
ALTER TABLE `universitydb`.`COURSE_BELONGS_TO` 
ADD CONSTRAINT `COURSE_BELONGS_TO_FK1`
  FOREIGN KEY (`COURSE_ID`)
  REFERENCES `universitydb`.`COURSE` (`COURSE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `COURSE_BELONGS_TO_FK2`
  FOREIGN KEY (`D_ID`)
  REFERENCES `universitydb`.`DEPARTMENT` (`D_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
