------------------------------------------------------------------
--  TABLE DEPARTMENT
------------------------------------------------------------------

CREATE TABLE DEPARTMENT
(
   D_ID            VARCHAR (10),
   D_NAME          VARCHAR (10),
   FACULTY_COUNT   NUMERIC,
   HOD             VARCHAR (10)
)
NOCACHE
LOGGING;



ALTER TABLE `DEPARTMENT` CHANGE `D_NAME` `D_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `universitydb`.`DEPARTMENT` 
CHANGE COLUMN `D_ID` `D_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `D_NAME` `D_NAME` VARCHAR(50) NOT NULL ,
CHANGE COLUMN `HOD` `HOD` VARCHAR(10) NULL ,
ADD PRIMARY KEY (`D_ID`),
ADD UNIQUE INDEX `D_ID_UNIQUE` (`D_ID` ASC);


ALTER TABLE `universitydb`.`DEPARTMENT` 
ADD INDEX `DEPARTMENT_FK_idx` (`HOD` ASC);
ALTER TABLE `universitydb`.`DEPARTMENT` 
ADD CONSTRAINT `DEPARTMENT_FK`
  FOREIGN KEY (`HOD`)
  REFERENCES `universitydb`.`FACULTY` (`P_UNITY_ID`)
  ON DELETE SET NULL
  ON UPDATE CASCADE;
