------------------------------------------------------------------
--  TABLE ENROLLS
------------------------------------------------------------------

CREATE TABLE ENROLLS
(
   COURSE_ID      VARCHAR (10),
   UNITY_ID       VARCHAR (10),
   TERM_ID        VARCHAR (10),
   GRADE_SCORED   CHAR (1)
)
NOCACHE
LOGGING;

ALTER TABLE `universitydb`.`ENROLLS` 
CHANGE COLUMN `COURSE_ID` `COURSE_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `UNITY_ID` `S_UNITY_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `TERM_ID` `TERM_ID` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`COURSE_ID`, `S_UNITY_ID`, `TERM_ID`);

ALTER TABLE `universitydb`.`ENROLLS` 
CHANGE COLUMN `TERM_ID` `TERM_ID` VARCHAR(10) NULL ,
ADD INDEX `ENROLLS_FK_2_idx` (`S_UNITY_ID` ASC),
ADD INDEX `ENROLLS_FK_3_idx` (`TERM_ID` ASC);
ALTER TABLE `universitydb`.`ENROLLS` 
ADD CONSTRAINT `ENROLLS_FK_1`
  FOREIGN KEY (`COURSE_ID`)
  REFERENCES `universitydb`.`COURSE` (`COURSE_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `ENROLLS_FK_2`
  FOREIGN KEY (`S_UNITY_ID`)
  REFERENCES `universitydb`.`Student` (`S_UNITY_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `ENROLLS_FK_3`
  FOREIGN KEY (`TERM_ID`)
  REFERENCES `universitydb`.`TERM` (`TERM_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE `universitydb`.`ENROLLS` 
CHANGE COLUMN `GRADE_SCORED` `GRADE_SCORED` VARCHAR(2) NULL DEFAULT NULL ;
