------------------------------------------------------------------
--  TABLE FACULTY
------------------------------------------------------------------

CREATE TABLE FACULTY
(
   P_UNITY_ID    VARCHAR (10),
   PROF_ID       VARCHAR (10),
   DESIGNATION   VARCHAR (10)
)
NOCACHE
LOGGING;


ALTER TABLE `universitydb`.`FACULTY` 
CHANGE COLUMN `P_UNITY_ID` `P_UNITY_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `PROF_ID` `PROF_ID` VARCHAR(10) NOT NULL ,
ADD UNIQUE INDEX `PROF_ID_UNIQUE` (`PROF_ID` ASC),
ADD PRIMARY KEY (`P_UNITY_ID`),
ADD UNIQUE INDEX `P_UNITY_ID_UNIQUE` (`P_UNITY_ID` ASC);

ALTER TABLE `universitydb`.`FACULTY` 
ADD CONSTRAINT `FACULTY_FK_1`
  FOREIGN KEY (`P_UNITY_ID`)
  REFERENCES `universitydb`.`PERSON` (`unity_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE `universitydb`.`FACULTY` 
CHANGE COLUMN `DESIGNATION` `DESIGNATION` VARCHAR(20) NULL DEFAULT NULL ;
