------------------------------------------------------------------
--  TABLE LECTURE_SLOTS
------------------------------------------------------------------

CREATE TABLE LECTURE_SLOTS
(
   SLOT_ID     VARCHAR (10),
   DAY_NAME    VARCHAR (10),
   FROM_TIME   TIMESTAMP (6),
   TO_TIME     TIMESTAMP (6)
)
NOCACHE
LOGGING;

ALTER TABLE `universitydb`.`LECTURE_SLOTS` 
CHANGE COLUMN `SLOT_ID` `SLOT_ID` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`SLOT_ID`),
ADD UNIQUE INDEX `SLOT_ID_UNIQUE` (`SLOT_ID` ASC);

ALTER TABLE `LECTURE_SLOTS` CHANGE `FROM_TIME` `FROM_TIME` TIME(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)';

ALTER TABLE `LECTURE_SLOTS` CHANGE `TO_TIME` `TO_TIME` TIME(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000';