------------------------------------------------------------------
--  TABLE PHONE
------------------------------------------------------------------

CREATE TABLE PHONE
(
   UNITY_ID     VARCHAR (10),
   PHONE_NUM    VARCHAR (10),
   PHONE_TYPE   VARCHAR (10)
)
NOCACHE
LOGGING;


ALTER TABLE `universitydb`.`PHONE` 
CHANGE COLUMN `UNITY_ID` `UNITY_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `PHONE_NUM` `PHONE_NUM` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `PHONE_TYPE` `PHONE_TYPE` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`UNITY_ID`, `PHONE_NUM`);

ALTER TABLE `universitydb`.`PHONE` 
ADD CONSTRAINT `UNITY_ID`
  FOREIGN KEY (`UNITY_ID`)
  REFERENCES `universitydb`.`PERSON` (`unity_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
