------------------------------------------------------------------
--  TABLE SCHEDULED_AT
------------------------------------------------------------------

CREATE TABLE SCHEDULED_AT
(
   COURSE_ID   VARCHAR (10),
   SLOT_ID     VARCHAR (10),
   ROOM_NO     VARCHAR (20)
)
NOCACHE
LOGGING;


ALTER TABLE `universitydb`.`SCHEDULED_AT` 
CHANGE COLUMN `COURSE_ID` `COURSE_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `SLOT_ID` `SLOT_ID` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`COURSE_ID`, `SLOT_ID`);

ALTER TABLE `universitydb`.`SCHEDULED_AT` 
ADD INDEX `SCHEDULED_AT_FK_2_idx` (`SLOT_ID` ASC);
ALTER TABLE `universitydb`.`SCHEDULED_AT` 
ADD CONSTRAINT `SCHEDULED_AT_FK_1`
  FOREIGN KEY (`COURSE_ID`)
  REFERENCES `universitydb`.`COURSE` (`COURSE_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `SCHEDULED_AT_FK_2`
  FOREIGN KEY (`SLOT_ID`)
  REFERENCES `universitydb`.`LECTURE_SLOTS` (`SLOT_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
