------------------------------------------------------------------
--  TABLE STUDENT
------------------------------------------------------------------

CREATE TABLE STUDENT
(
   S_UNITY_ID    VARCHAR (10),
   S_ID          VARCHAR (10),
   DEGREE_TYPE   VARCHAR (10),
   ADVISOR_ID    VARCHAR (10),
   CGPA          NUMERIC
)
NOCACHE
LOGGING;


ALTER TABLE `universitydb`.`Student` 
ADD PRIMARY KEY (`S_UNITY_ID`);

ALTER TABLE `universitydb`.`Student` 
CHANGE COLUMN `DEGREE_TYPE` `DEGREE_TYPE` VARCHAR(10) NULL ,
CHANGE COLUMN `ADVISOR_ID` `ADVISOR_ID` VARCHAR(10) NULL ,
CHANGE COLUMN `CGPA` `CGPA` DECIMAL(10,0) NULL ,
ADD UNIQUE INDEX `S_ID_UNIQUE` (`S_ID` ASC);

ALTER TABLE `universitydb`.`Student` 
ADD INDEX `STUDENT_FK_2_idx` (`ADVISOR_ID` ASC);
ALTER TABLE `universitydb`.`Student` 
ADD CONSTRAINT `STUDENT_FK_1`
  FOREIGN KEY (`S_UNITY_ID`)
  REFERENCES `universitydb`.`PERSON` (`unity_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `STUDENT_FK_2`
  FOREIGN KEY (`ADVISOR_ID`)
  REFERENCES `universitydb`.`FACULTY` (`P_UNITY_ID`)
  ON DELETE SET NULL
  ON UPDATE CASCADE;
