------------------------------------------------------------------
--  TABLE TEACHES
------------------------------------------------------------------

CREATE TABLE TEACHES
(
   COURSE_ID   VARCHAR (10),
   PROF_ID     VARCHAR (10),
   TERM_ID     VARCHAR (10)
)
NOCACHE
LOGGING;

ALTER TABLE `universitydb`.`TEACHES` 
CHANGE COLUMN `COURSE_ID` `COURSE_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `PROF_ID` `PROF_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `TERM_ID` `TERM_ID` VARCHAR(10) NOT NULL ,
ADD PRIMARY KEY (`COURSE_ID`, `PROF_ID`, `TERM_ID`);

ALTER TABLE `universitydb`.`TEACHES` 
CHANGE COLUMN `PROF_ID` `P_UNITY_ID` VARCHAR(10) NOT NULL ;


ALTER TABLE `universitydb`.`TEACHES` 
ADD INDEX `TEACHES_FK_1_idx` (`P_UNITY_ID` ASC),
ADD INDEX `TEACHES_FK_3_idx` (`TERM_ID` ASC);
ALTER TABLE `universitydb`.`TEACHES` 
ADD CONSTRAINT `TEACHES_FK_1`
  FOREIGN KEY (`P_UNITY_ID`)
  REFERENCES `universitydb`.`FACULTY` (`P_UNITY_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `TEACHES_FK_2`
  FOREIGN KEY (`COURSE_ID`)
  REFERENCES `universitydb`.`COURSE` (`COURSE_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `TEACHES_FK_3`
  FOREIGN KEY (`TERM_ID`)
  REFERENCES `universitydb`.`TERM` (`TERM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
