------------------------------------------------------------------
--  TABLE TERM
------------------------------------------------------------------

CREATE TABLE TERM
(
   TERM_ID      VARCHAR (10),
   TERM_NAME    VARCHAR (10),
   START_DATE   DATE,
   END_DATE     DATE
)
NOCACHE
LOGGING;


ALTER TABLE `universitydb`.`TERM` 
CHANGE COLUMN `TERM_ID` `TERM_ID` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `TERM_NAME` `TERM_NAME` VARCHAR(10) NOT NULL ,
CHANGE COLUMN `START_DATE` `START_DATE` DATE NOT NULL ,
CHANGE COLUMN `END_DATE` `END_DATE` DATE NOT NULL ,
ADD PRIMARY KEY (`TERM_ID`),
ADD UNIQUE INDEX `TERM_ID_UNIQUE` (`TERM_ID` ASC);
